baseURL = "https://hanazonochateau.net/"
languageCode = "ja-jp"
title = "花園シャトー107号室"
theme = "etch"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
publishDir = "docs"
canonifyurls = true

[markup]
defaultMarkdownHandler = "blackfriday"
[markup.blackFriday]
hrefTargetBlank = true

[params]
copyright = "Copyright © 2022 HIROSE Tomoyuki"
dark = "on"
highlight = true
commentForm = "https://forms.gle/Cc3R3fFMCQ9m6Rsr9"
topHitokoto = "毎日眠いです。"

[menu]
[[menu.main]]
identifier = "posts"
name = "posts"
title = "posts"
url = "/"
weight = 10

[[menu.main]]
identifier = "575"
name = "575"
title = "575"
url = "/575"
weight = 15

[[menu.main]]
identifier = "about"
name = "about"
title = "about"
url = "/about"
weight = 20

[[menu.main]]
identifier = "comments"
name = "comments"
title = "comments"
url = "/comments"
weight = 25

[permalinks]
posts = "/:title/"
